{% set name = "scipy-stubs" %}
{% set version = "1.14.1.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scipy_stubs-{{ version }}.tar.gz
  sha256: 215a2c9d865e355a5c5cc088ec6d87f489a584396256113d72d7d24cfb0e889c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - optype >=0.7.1
  run_constrained:
    - scipy >=1.10

test:
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/jorenham/scipy-stubs/
  summary: Typing Stubs for SciPy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lucascolley
    - jorenham
