{% set version = "1.14.1.5" %}
{% set scipy_version = version.rsplit('.', 1)[0] %}
{% set python_min = "3.10" %}

package:
  name: scipy-stubs-split
  version: {{ version }}

source:
#   url: https://pypi.org/packages/source/s/scipy-stubs/scipy_stubs-{{ version }}.tar.gz
#   sha256: 66c160c6b72b1406edc7827879ef25ea81dc3d95ab7e4af3a2de836f27c26ce6
  git_url: https://github.com/jorenham/scipy-stubs.git

build:
  number: 1

requirements:
  build:
    - python

outputs:
  - name: scipy-stubs
    script: build-output.sh
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - hatchling
        - pip
      run:
        - python >={{ python_min }},<4.0.0
        - optype >=0.7.3
      run_constrained:
        - scipy >=1.10
    test:
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: scipy-typed
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - scipy =={{ scipy_version }}
        - {{ pin_subpackage('scipy-stubs', exact=True) }}
    test:
      requires:
        - basedmypy
      imports:
        - scipy
      source_files:
        - pyproject.toml
        - .mypyignore
      commands:
        - stubtest --mypy-config-file=pyproject.toml --allowlist=.mypyignore --ignore-unused-allowlist scipy

about:
  home: https://github.com/jorenham/scipy-stubs/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Precise type hints for all of SciPy.
  description: |
    Stubs package providing type annotations and static type checking support for SciPy, 
    enabling improved type inference and static analysis for scientific computing and 
    numerical programming in modern Python.

  dev_url: https://github.com/jorenham/scipy-stubs/
  doc_url: https://github.com/jorenham/scipy-stubs?tab=readme-ov-file#scipy-stubs
  doc_source_url: https://github.com/jorenham/scipy-stubs/blob/master/README.md#scipy-stubs

extra:
  recipe-maintainers:
    - lucascolley
    - jorenham
  feedstock-name: scipy-stubs
