{% set version = "1.15.1.0" %}
{% set scipy_version = version.rsplit('.', 1)[0] %}
{% set python_min = "3.10" %}

package:
  name: scipy-stubs-split
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/s/scipy-stubs/scipy-stubs-{{ version }}.tar.gz
  sha256: 25756486635594025ed3249b6fb659c29dc5874c7b55565ad248b13a4ff4fa1c

build:
  number: 0

outputs:
  - name: scipy-stubs
    build:
      noarch: python
      script: pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python {{ python_min }}
        - hatchling
        - pip
      run:
        - python >={{ python_min }},<4.0.0
        - optype >=0.8.0
      run_constrained:
        - scipy >=1.15.1,<1.16.0
    test:
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: scipy-typed
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }},<4.0.0
        - scipy =={{ scipy_version }}
        - {{ pin_subpackage('scipy-stubs', exact=True) }}
    test:
      requires:
        - python {{ python_min }}
        - basedmypy
      imports:
        - scipy
      files:
        - .mypyignore-extra
      source_files:
        - pyproject.toml
        - .mypyignore
      commands:
        - stubtest --mypy-config-file=pyproject.toml --allowlist=.mypyignore --allowlist=.mypyignore-extra --ignore-unused-allowlist scipy

about:
  home: https://github.com/jorenham/scipy-stubs/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Precise type hints for all of SciPy.
  description: |
    Stubs package providing type annotations and static type checking support for SciPy, 
    enabling improved type inference and static analysis for scientific computing and 
    numerical programming in modern Python.

  dev_url: https://github.com/jorenham/scipy-stubs/
  doc_url: https://github.com/jorenham/scipy-stubs?tab=readme-ov-file#scipy-stubs
  doc_source_url: https://github.com/jorenham/scipy-stubs/blob/master/README.md#scipy-stubs

extra:
  recipe-maintainers:
    - lucascolley
    - jorenham
  feedstock-name: scipy-stubs
