{% set name = "scipy-stubs" %}
{% set version = "1.14.1.6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scipy_stubs-{{ version }}.tar.gz
  sha256: 7505ea8a1624ab4c72516a04eb2838f5ae43e33ba100fc2d5c44103003dd414a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - optype >=0.7.3
  run_constrained:
    - scipy >=1.10

test:
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/jorenham/scipy-stubs/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Precise type hints for all of SciPy.
  description: |
    Stubs package providing type annotations and static type checking support for SciPy, 
    enabling improved type inference and static analysis for scientific computing and 
    numerical programming in modern Python.

  dev_url: https://github.com/jorenham/scipy-stubs/
  doc_url: https://github.com/jorenham/scipy-stubs?tab=readme-ov-file#scipy-stubs
  doc_source_url: https://github.com/jorenham/scipy-stubs/blob/master/README.md#scipy-stubs

extra:
  recipe-maintainers:
    - lucascolley
    - jorenham
