schema_version: 1

context:
  stubs_version: 3
  scipy_version: 1.16.2
  scipy_cap: 1.17.0
  python_min: 3.11
  optype_min: 0.14.0
  optype_cap: 0.15.0
  mypy_version: 1.18.1

recipe:
  name: scipy-stubs-split
  version: ${{ scipy_version }}.${{ stubs_version }}

source:
  url: https://files.pythonhosted.org/packages/source/s/scipy-stubs/scipy_stubs-${{ scipy_version }}.${{ stubs_version }}.tar.gz
  sha256: b1afd21442699b8bdd399508187bddcedc6c29a34b188fd603396cb6754c2a91

build:
  number: 0

outputs:
  - package:
      name: scipy-stubs
    build:
      noarch: python
      script: pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python ${{ python_min }}.*
        - uv-build
        - pip
      run:
        - python >=${{ python_min }}
        - optype-numpy >=${{ optype_min }}, <${{ optype_cap }}
      run_constraints:
        - scipy >=${{ scipy_version }}, <${{ scipy_cap }}
    tests:
      - requirements:
          run:
            - python ${{ python_min }}.*
            - pip
        script:
          - pip check

  - package:
      name: scipy-typed
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - scipy ==${{ scipy_version }}
        - ${{ pin_subpackage('scipy-stubs', exact=True) }}
    tests:
      - python:
          imports:
            - scipy
      - files:
          recipe:
            - .mypyignore-extra
          source:
            - pyproject.toml
            - .mypyignore
        requirements:
          run:
            - python ${{ python_min }}.*
            - array-api-compat
            - mypy ==${{ mypy_version }}
        script:
          - stubtest --allowlist=.mypyignore --allowlist=.mypyignore-extra scipy

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Typing Stubs for SciPy
  description: |
    Stubs package providing type annotations and static type checking support for SciPy,
    enabling improved type inference and static analysis for scientific computing and
    numerical programming in modern Python.

  homepage: https://github.com/scipy/scipy-stubs/
  repository: https://github.com/scipy/scipy-stubs/
  documentation: https://github.com/scipy/scipy-stubs?tab=readme-ov-file#scipy-stubs

extra:
  recipe-maintainers:
    - lucascolley
    - jorenham
  feedstock-name: scipy-stubs
